### ISSUE TITLE
Issues with installing FEW for GPU capability on computing cluster

### ISSUE THREAD

**Issue by AminBoumerdassi** [BlackHolePerturbationToolkit/FastEMRIWaveforms#69]
I'm attempting to install FEW with GPU capability on a remote computing cluster with A100s so I had to slightly adapt the installation instructions. To install, I did:

```
$ module purge
$ module load Miniconda3/22.11.1-1
$ conda create -n few_env -c conda-forge gcc_linux-64 gxx_linux-64 wget gsl lapack=3.6.1 hdf5 numpy Cython scipy tqdm jupyter ipython h5py requests matplotlib python=3.7 --solver=libmamba 
$ source activate few_env
$ conda install -c nvidia cuda-nvcc==11.6.55 --solver=libmamba
$ pip install cupy-cuda11x==11.6.0
$ cd /nesi/project/uoa00195/software
$ git clone https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms.git
$ FastEMRIWaveforms
$ python setup.py install --ccbin /nesi/project/uoa00195/conda_envs/few_env/bin/x86_64-conda_cos6-linux-gnu-gcc
```

I then attempt to test that FEW has been successfully installed with ``` python -m unittest discover ```. For this, I did:

```
$ module load Miniconda3
$ source activate few_env
$ cd /nesi/project/uoa00195/software/FastEMRIWaveforms
$ module load CUDA/11.6.2
$ python -m unittest discover
$
```

But this gives the following error message

```
======================================================================
ERROR: test_aak (few.tests.test_aak.AAKWaveformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/tests/test_aak.py", line 66, in test_aak
    wave_gpu = Pn5AAKWaveform(inspiral_kwargs, sum_kwargs, use_gpu=True)
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 1264, in __init__
    num_threads=num_threads,
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 1024, in __init__
    self.create_waveform = sum_module(**sum_kwargs)
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/summation/aakwave.py", line 82, in __init__
    self.waveform_generator = pyWaveform_gpu
NameError: name 'pyWaveform_gpu' is not defined

======================================================================
ERROR: test_detector_frame (few.tests.test_detector_wave.WaveformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/tests/test_detector_wave.py", line 28, in test_detector_frame
    "FastSchwarzschildEccentricFlux", **waveform_kwargs
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 87, in __init__
    self.waveform_generator = waveform(*args, **kwargs)
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 831, in __init__
    **kwargs,
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 441, in __init__
    self.amplitude_generator = amplitude_module(**amplitude_kwargs)
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/amplitude/romannet.py", line 145, in __init__
    self.neural_layer = neural_layer_wrap
NameError: name 'neural_layer_wrap' is not defined

======================================================================
ERROR: test_fast_and_slow (few.tests.test_few.WaveformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/tests/test_few.py", line 59, in test_fast_and_slow
    use_gpu=gpu_available,
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 831, in __init__
    **kwargs,
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/waveform.py", line 441, in __init__
    self.amplitude_generator = amplitude_module(**amplitude_kwargs)
  File "/scale_wlg_persistent/filesets/project/uoa00195/software/FastEMRIWaveforms/few/amplitude/romannet.py", line 145, in __init__
    self.neural_layer = neural_layer_wrap
NameError: name 'neural_layer_wrap' is not defined

----------------------------------------------------------------------
Ran 7 tests in 6.305s

FAILED (errors=3)
```

I'm unsure what's causing this problem. Could this be to do with the version of CUDA used? Is there a maximum version that FEW is tested to?

**Comment by mikekatz04** [comment]
Technically there is, but this is probably related to the setup.py file not finding the cuda home directory. 

The errors you are getting either mean cupy is not found, it is not the right version, or the GPU code is not installed properly. The error is more cryptic than it should be. I need to update that. 

This is the locate cuda function in setup.py:
```
def locate_cuda():
    """Locate the CUDA environment on the system
    Returns a dict with keys 'home', 'nvcc', 'include', and 'lib64'
    and values giving the absolute path to each directory.
    Starts by looking for the CUDAHOME env variable. If not found,
    everything is based on finding 'nvcc' in the PATH.
    """

    # First check if the CUDAHOME env variable is in use
    if "CUDAHOME" in os.environ or "CUDA_HOME" in os.environ:
        try:
            home = os.environ["CUDAHOME"]
        except KeyError:
            home = os.environ["CUDA_HOME"]

        nvcc = pjoin(home, "bin", "nvcc")
    else:
        # Otherwise, search the PATH for NVCC
        nvcc = find_in_path("nvcc", os.environ["PATH"])
        if nvcc is None:
            raise EnvironmentError(
                "The nvcc binary could not be "
                "located in your $PATH. Either add it to your path, "
                "or set $CUDAHOME"
            )
        home = os.path.dirname(os.path.dirname(nvcc))

    cudaconfig = {
        "home": home,
        "nvcc": nvcc,
        "include": pjoin(home, "include"),
        "lib64": pjoin(home, "lib64"),
    }
    for k, v in iter(cudaconfig.items()):
        if not os.path.exists(v):
            raise EnvironmentError(
                "The CUDA %s path could not be " "located in %s" % (k, v)
            )

    return cudaconfig
```

Make sure the environmental variables are set properly. If that does not work, I would recommend putting a breakpoint in that function in setup.py to see why it is not finding them.

**Comment by AminBoumerdassi** [comment]
For some reason, what I cloned from the repo was not exactly as its current state. Pulling the current repo resulted in a working installation, and no issues with GPU capability. Thanks for your help!
