### ISSUE TITLE
undefined symbol: LAPACKE_dgtsv

### ISSUE THREAD

**Issue by pbacon42** [BlackHolePerturbationToolkit/FastEMRIWaveforms#8]
Hi. I am pretty sure I installed the library correctly but I get the following error when importing:

```
> python3.8 
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from few.waveform import GenerateEMRIWaveform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philippe/Desktop/LISA/FastEMRIWaveforms/few/waveform.py", line 41, in <module>
    from few.summation.aakwave import AAKSummation
  File "/home/philippe/Desktop/LISA/FastEMRIWaveforms/few/summation/aakwave.py", line 48, in <module>
    from few.summation.interpolatedmodesum import CubicSplineInterpolant
  File "/home/philippe/Desktop/LISA/FastEMRIWaveforms/few/summation/interpolatedmodesum.py", line 30, in <module>
    from pyinterp_cpu import interpolate_arrays_wrap as interpolate_arrays_wrap_cpu
ImportError: /usr/local/lib/python3.8/dist-packages/few-1.2.1-py3.8-linux-x86_64.egg/pyinterp_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: LAPACKE_dgtsv
```

I think it is due to the linking with the LAPACKE library so I did:

```
> ldd /usr/lib/x86_64-linux-gnu/liblapacke.so
        linux-vdso.so.1 (0x00007ffd9e3f3000)
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f59fa9fd000)
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f59fa13e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f59f9d4d000)
        libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f59f996e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f59f95d0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f59f93b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f59fb3ef000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f59f9178000)
```

So everything seem to be linked properly. I have compared this last output with a colleague who had no problem of this kind and she has many more lines of binary files. Here is her output :

```
       linux-vdso.so.1 (0x00007ffc537ef000)
       liblapacke.so.3 => /usr/lib/x86_64-linux-gnu/liblapacke.so.3 (0x00007fbe6b455000)
       libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fbe6b415000)
       libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbe6b248000)
       libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbe6b0dd000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe6af18000)
       libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007fbe6aeab000)
       liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007fbe6a806000)
       libtmglib.so.3 => /usr/lib/x86_64-linux-gnu/libtmglib.so.3 (0x00007fbe6a7a3000)
       libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe6a79d000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe6a77b000)
       /lib64/ld-linux-x86-64.so.2 (0x00007fbe6b6af000)
       libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbe6a761000)
       libgfortran.so.5 => /usr/lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007fbe6a4ab000)
       libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fbe6a460000)
```

She is using python3.9 but just mentioning.... 

Is there any additional linking to do inside the setup.py ?

Config: Ubuntu 18.04, python3.8

Thank you in advance for your assistance.

**Comment by mikekatz04** [comment]
Did you install everything as instructed in the conda environment? The main reason for using the conda environment is to manage these dependencies and linking.

**Comment by mikekatz04** [comment]
If you are using your own lapack installation then, at this point, you will need to provide extra command line arguments to setup.py install (or you can open an adjust the setup.py file). An example of this is shown in the README. However, this has not been extensively tested. We generally recommend to work in a conda environment so that all the dependencies / linking are managed intrinsically.

**Comment by pbacon42** [comment]
Ok I solved it thanks to Maude. 

The fact is that we do need the `-llapacke` linking and it was not in my log.
For me ithe llapacke package exists but it is not called at linking step.

The fix is super easy: add `lapacke` in the list named `libraries` at line 309 of the setup.py.
Then clean any existing binary file in the `/build` directory and recompile` with a `python setup.py install`

Hopefully this can help users who, like me, did not installed the package with conda...

**Comment by esavalle** [comment]
Thanks, It worked.

**Comment by mikekatz04** [comment]
Great. Thank you for looking at this @pbacon42! I will add this to the setup file and close this issue.
